#
# Makefile for sunxi specific clk
#

obj-y += clk-factors.o clk-periph.o clk-default.o
obj-${CONFIG_COMMON_CLK_DEBUG} += clk-debugfs.o
obj-${CONFIG_ARCH_SUN8IW1} += clk-sun8iw1.o
obj-${CONFIG_ARCH_SUN8IW3} += clk-sun8iw3.o
obj-${CONFIG_ARCH_SUN9IW1} += clk-sun9iw1.o
